repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-docstring-first

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        args:
          - --strict
          - --ignore-missing-imports
        additional_dependencies:
          - types-click
          - types-python-dateutil
        exclude: ^tests/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args:
          - --disable=missing-docstring
        require_serial: true
        exclude: ^tests/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.10"
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
